sudo: required # this is required for docker usage
services:
  - docker

before_install: # before installing any dependencies
  - docker build -t joomrise/docker-react -f Dockerfile.dev . # tagging our image and defining custom Dockerfile

script: # build fails if any of the scripts bellow throws an error or returns non-0 value
  - docker run joomrise/docker-react npm run test -- --coverage # coverage allows us to exit the tests and returns a status


deploy:
  provider: elasticbeanstalk # travis has support of multiple platforms
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-661200370736" # this is kind of a harddrive id where the zipped app will be stored
  bucket_path: "docker-react"
  on:
    branch: master # deploy on master branch update
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
